site_name: Documentation portal
site_description: the central documentation portal for our OSS projects
site_url: https://pibico.github.io/portal/

theme:
  name: material
  logo: assets/images/logo.png
  favicon: assets/images/favicon.png
  language: es
  features:
    - navigation.sections      # Sidebar organizado por secciones
    - navigation.tabs          # Navegación tipo pestañas
    - search.highlight         # Resaltar palabras buscadas
    - search.suggest           # Sugerencias en búsqueda

plugins:
  - search

nav:
  - Home: index.md
  - About pibiCo: about.md
  - Projects:
      - PibiCut:
          - Inicio: projects/pibicut/index.md
          - Guía: projects/pibicut/guide.md

extra:
  homepage: https://www.pibico.es
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/pibico
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/pibico
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCZ_aFZHXy-fIXBoyLyHollg  

copyright: >
  © 2026 pibiCo · Documentation portal for our OSS projects
