site_name: pibiCo - Documentation portal
site_description: pibiCo documentation portal for OSS projects
site_url: https://pibico.github.io/portal/

theme:
  name: material
  logo: assets/images/logo.png
  favicon: assets/images/favicon.ico
  language: en
  palette:
    scheme: slate
    primary: black
    accent: light blue
  features:
    - navigation.tabs          # Navegación tipo pestañas
    - navigation.tabs.sticky   # Tabs visibles siempre
    - navigation.path          # Incluye navegación de migas de pan
    - navigation.prune         # Poda páginas que no están en uso 
    - toc.follow               # Anclajes - barra lateral se desplaza automáticamente de modo que el anclaje activo siempre esté visible
    - toc.integrate            # se representa como parte de la barra lateral de navegación de la izquierda
    - search.highlight         # Resaltar palabras buscadas
    - search.suggest           # Sugerencias en búsqueda
    - navigation.footer        # Navegación inferior a página anterior y siguiente

plugins:
  - search
  - optimize
  - social:
      cards_layout_dir: layouts
      cards_layout: custom
      debug: true


nav:
  - Home: index.md
  - About pibiCo: about.md
  - Apps:
      - pibiCut: apps/pibicut/index.md
      - pibiCal: apps/pibical/index.md
      - pibiCard: apps/pibicard/index.md
      - pibiDAV: apps/pibidav/index.md
      - pibiDesk: apps/pibidesk/index.md
      - pibiOffline: apps/pibioffline/index.md
      - Guides:
        - pibiCut: apps/pibicut/guide.md
        - pibiCal: apps/pibical/guide.md
        - pibiCard: apps/pibicard/guide.md
        - pibiDAV: apps/pibidav/guide.md
        - pibiDesk: apps/pibidesk/guide.md
        - pibiOffline: apps/pibioffline/guide.md

extra_css:
  - stylesheets/extra.css

extra:
  homepage: https://www.pibico.es
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/pibico
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/pibico
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCZ_aFZHXy-fIXBoyLyHollg  

copyright: >
  © 2026 pibiCo · Documentation portal for our OSS projects
